import { db } from "@workspace/db";
import {
  categoriesTable,
  productsTable,
  wilayasTable,
  citiesTable,
  type InsertCategory,
  type InsertProduct,
  type InsertWilaya,
  type InsertCity,
} from "@workspace/db/schema";

async function seed() {
  const seedMode = process.env.SEED_MODE === "bootstrap" ? "bootstrap" : "reset";
  console.log(`Seeding database in ${seedMode} mode...`);

  if (seedMode === "reset") {
    await db.delete(productsTable);
    await db.delete(categoriesTable);
    await db.delete(citiesTable);
    await db.delete(wilayasTable);
    console.log("Cleared existing catalog and region data");
  }

  // Categories
  const categorySeeds: InsertCategory[] = [
    {
      name: "Electronics",
      nameAr: "إلكترونيات",
      nameFr: "Électronique",
      slug: "electronics",
      description: "Smartphones, laptops, tablets and more",
      descriptionAr: "هواتف ذكية، حواسيب محمولة، أجهزة لوحية والمزيد",
      descriptionFr: "Smartphones, ordinateurs portables, tablettes et plus",
      icon: "📱",
      image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=80",
    },
    {
      name: "Clothing & Fashion",
      nameAr: "ملابس وأزياء",
      nameFr: "Vêtements & Mode",
      slug: "clothing",
      description: "Traditional and modern clothing for all",
      descriptionAr: "ملابس تقليدية وعصرية للجميع",
      descriptionFr: "Vêtements traditionnels et modernes pour tous",
      icon: "👕",
      image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800&q=80",
    },
    {
      name: "Home & Kitchen",
      nameAr: "المنزل والمطبخ",
      nameFr: "Maison & Cuisine",
      slug: "home-kitchen",
      description: "Furniture, appliances and kitchen essentials",
      descriptionAr: "أثاث، أجهزة منزلية ومستلزمات المطبخ",
      descriptionFr: "Meubles, appareils et essentiels de cuisine",
      icon: "🏠",
      image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    },
    {
      name: "Beauty & Personal Care",
      nameAr: "الجمال والعناية الشخصية",
      nameFr: "Beauté & Soins",
      slug: "beauty",
      description: "Cosmetics, skincare and personal care products",
      descriptionAr: "مستحضرات التجميل والعناية بالبشرة",
      descriptionFr: "Cosmétiques, soins de la peau et produits personnels",
      icon: "💄",
      image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80",
    },
    {
      name: "Sports & Outdoors",
      nameAr: "الرياضة والأنشطة الخارجية",
      nameFr: "Sports & Plein Air",
      slug: "sports",
      description: "Sports equipment and outdoor gear",
      descriptionAr: "معدات رياضية وأدوات للأنشطة الخارجية",
      descriptionFr: "Équipements sportifs et matériel de plein air",
      icon: "⚽",
      image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800&q=80",
    },
    {
      name: "Food & Groceries",
      nameAr: "الطعام والبقالة",
      nameFr: "Alimentation & Épicerie",
      slug: "food",
      description: "Authentic Algerian food products and groceries",
      descriptionAr: "منتجات غذائية جزائرية أصيلة وبقالة",
      descriptionFr: "Produits alimentaires algériens authentiques et épicerie",
      icon: "🛒",
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
    },
    {
      name: "Books & Education",
      nameAr: "الكتب والتعليم",
      nameFr: "Livres & Éducation",
      slug: "books",
      description: "Books, stationery and educational materials",
      descriptionAr: "كتب، قرطاسية ومواد تعليمية",
      descriptionFr: "Livres, papeterie et matériaux éducatifs",
      icon: "📚",
      image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
    },
    {
      name: "Toys & Games",
      nameAr: "الألعاب والترفيه",
      nameFr: "Jouets & Jeux",
      slug: "toys",
      description: "Toys, games and entertainment for all ages",
      descriptionAr: "ألعاب وترفيه لجميع الأعمار",
      descriptionFr: "Jouets, jeux et divertissement pour tous les âges",
      icon: "🎮",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    },
    {
      name: "Automotive",
      nameAr: "السيارات والإكسسوارات",
      nameFr: "Automobile",
      slug: "automotive",
      description: "Car accessories, tools and spare parts",
      descriptionAr: "إكسسوارات السيارات والأدوات وقطع الغيار",
      descriptionFr: "Accessoires auto, outils et pièces détachées",
      icon: "🚗",
      image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80",
    },
    {
      name: "Handicrafts & Art",
      nameAr: "الحرف اليدوية والفن",
      nameFr: "Artisanat & Art",
      slug: "handicrafts",
      description: "Traditional Algerian handicrafts and artworks",
      descriptionAr: "الحرف اليدوية الجزائرية التقليدية والأعمال الفنية",
      descriptionFr: "Artisanat et œuvres d'art algériens traditionnels",
      icon: "🎨",
      image: "https://images.unsplash.com/photo-1606722590583-6951b5ea92ab?w=800&q=80",
    },
  ];

  const existingCategories = seedMode === "bootstrap" ? await db.select().from(categoriesTable) : [];
  const existingCategorySlugs = new Set(existingCategories.map((category) => category.slug));
  const missingCategories = categorySeeds.filter((category) => !existingCategorySlugs.has(category.slug));

  if (missingCategories.length > 0) {
    await db.insert(categoriesTable).values(missingCategories);
  }

  const categories = await db.select().from(categoriesTable);
  if (seedMode === "reset") {
    console.log(`Inserted ${categories.length} categories`);
  } else if (missingCategories.length > 0) {
    console.log(`Inserted ${missingCategories.length} missing categories`);
  } else {
    console.log(`Skipped categories; ${categories.length} already present`);
  }

  const catMap: Record<string, number> = {};
  for (const c of categories) {
    catMap[c.slug] = c.id;
  }

  // Products - comprehensive list
  const productSeeds: InsertProduct[] = [
    // Electronics
    {
      name: "Samsung Galaxy A54",
      nameAr: "سامسونج جالاكسي A54",
      nameFr: "Samsung Galaxy A54",
      slug: "samsung-galaxy-a54",
      description: "A powerful mid-range smartphone with excellent camera and long battery life.",
      descriptionAr: "هاتف ذكي متوسط الفئة قوي مع كاميرا ممتازة وبطارية طويلة الأمد.",
      descriptionFr: "Un smartphone milieu de gamme puissant avec une excellente caméra et une longue autonomie.",
      price: "75000",
      originalPrice: "89000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80",
      images: [
        "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80",
        "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&q=80",
      ],
      categoryId: catMap["electronics"],
      inStock: true,
      stockQuantity: 45,
      rating: "4.5",
      reviewCount: 128,
      isFeatured: true,
      discount: 16,
      brand: "Samsung",
      sku: "SAM-A54-128",
      tags: ["smartphone", "samsung", "android"],
      specifications: { "RAM": "8 GB", "Storage": "128 GB", "Camera": "50 MP", "Battery": "5000 mAh", "Display": "6.4 inch AMOLED" },
    },
    {
      name: "Apple iPhone 13",
      nameAr: "آبل آيفون 13",
      nameFr: "Apple iPhone 13",
      slug: "apple-iphone-13",
      description: "Premium smartphone with A15 Bionic chip and dual camera system.",
      descriptionAr: "هاتف ذكي متميز بمعالج A15 بيونيك ونظام كاميرا مزدوج.",
      descriptionFr: "Smartphone premium avec puce A15 Bionic et double système de caméra.",
      price: "145000",
      originalPrice: "165000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1632633173522-47456de71b76?w=600&q=80",
      images: [
        "https://images.unsplash.com/photo-1632633173522-47456de71b76?w=600&q=80",
        "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&q=80",
      ],
      categoryId: catMap["electronics"],
      inStock: true,
      stockQuantity: 22,
      rating: "4.8",
      reviewCount: 256,
      isFeatured: true,
      discount: 12,
      brand: "Apple",
      sku: "APL-IP13-128",
      tags: ["smartphone", "apple", "ios"],
      specifications: { "Chip": "A15 Bionic", "Storage": "128 GB", "Camera": "12 MP Dual", "Battery": "3227 mAh", "Display": "6.1 inch Super Retina XDR" },
    },
    {
      name: "Laptop Lenovo IdeaPad 3",
      nameAr: "لابتوب لينوفو آيديابد 3",
      nameFr: "Ordinateur Portable Lenovo IdeaPad 3",
      slug: "lenovo-ideapad-3",
      description: "Reliable laptop for work and study with Intel Core i5 processor.",
      descriptionAr: "لابتوب موثوق للعمل والدراسة بمعالج Intel Core i5.",
      descriptionFr: "Ordinateur portable fiable pour le travail et les études avec processeur Intel Core i5.",
      price: "95000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80",
      images: [
        "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80",
      ],
      categoryId: catMap["electronics"],
      inStock: true,
      stockQuantity: 18,
      rating: "4.3",
      reviewCount: 89,
      isFeatured: false,
      brand: "Lenovo",
      sku: "LNV-IP3-I5",
      tags: ["laptop", "lenovo", "computer"],
      specifications: { "Processor": "Intel Core i5", "RAM": "8 GB DDR4", "Storage": "512 GB SSD", "Display": "15.6 inch FHD", "OS": "Windows 11" },
    },
    {
      name: "Headphones Sony WH-1000XM4",
      nameAr: "سماعات سوني WH-1000XM4",
      nameFr: "Casque Sony WH-1000XM4",
      slug: "sony-wh1000xm4",
      description: "Industry-leading noise cancellation wireless headphones.",
      descriptionAr: "سماعات لاسلكية بخاصية إلغاء الضوضاء الرائدة في الصناعة.",
      descriptionFr: "Casque sans fil à réduction de bruit leader de l'industrie.",
      price: "42000",
      originalPrice: "52000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&q=80",
      images: [
        "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&q=80",
      ],
      categoryId: catMap["electronics"],
      inStock: true,
      stockQuantity: 30,
      rating: "4.7",
      reviewCount: 203,
      isFeatured: true,
      discount: 19,
      brand: "Sony",
      sku: "SNY-WH1000XM4",
      tags: ["headphones", "sony", "wireless", "noise-cancelling"],
      specifications: { "Type": "Over-ear", "Connectivity": "Bluetooth 5.0", "Battery": "30 hours", "Driver": "40 mm" },
    },
    {
      name: "Smart TV Samsung 55 inch 4K",
      nameAr: "تلفاز ذكي سامسونج 55 بوصة 4K",
      nameFr: "TV Samsung 55 pouces 4K Smart",
      slug: "samsung-tv-55-4k",
      description: "Crystal clear 4K Smart TV with HDR and built-in streaming apps.",
      descriptionAr: "تلفاز ذكي بدقة 4K فائقة الوضوح مع HDR وتطبيقات البث المدمجة.",
      descriptionFr: "Smart TV 4K ultra-claire avec HDR et applications de streaming intégrées.",
      price: "128000",
      originalPrice: "145000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&q=80"],
      categoryId: catMap["electronics"],
      inStock: true,
      stockQuantity: 12,
      rating: "4.6",
      reviewCount: 74,
      isFeatured: true,
      discount: 12,
      brand: "Samsung",
      sku: "SAM-TV55-4K",
      tags: ["tv", "smart tv", "samsung", "4k"],
      specifications: { "Size": "55 inch", "Resolution": "4K UHD", "HDR": "HDR10+", "OS": "Tizen" },
    },
    // Clothing
    {
      name: "Traditional Burnous",
      nameAr: "برنوس تقليدي",
      nameFr: "Burnous Traditionnel",
      slug: "traditional-burnous",
      description: "Authentic Algerian burnous handmade from premium wool, perfect for cold seasons.",
      descriptionAr: "برنوس جزائري أصيل مصنوع يدويًا من الصوف الفاخر، مثالي لفصل الشتاء.",
      descriptionFr: "Burnous algérien authentique fait à la main en laine premium, parfait pour la saison froide.",
      price: "8500",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=600&q=80"],
      categoryId: catMap["clothing"],
      inStock: true,
      stockQuantity: 25,
      rating: "4.9",
      reviewCount: 156,
      isFeatured: true,
      brand: "Artisan Algérien",
      sku: "CLT-BRN-WL",
      tags: ["burnous", "traditional", "algerian", "wool"],
      specifications: { "Material": "Pure Wool", "Size": "M, L, XL, XXL", "Origin": "Algeria" },
    },
    {
      name: "Men's Djellaba",
      nameAr: "جلابة رجالية",
      nameFr: "Djellaba Homme",
      slug: "mens-djellaba",
      description: "Classic Algerian men's djellaba in white cotton, ideal for formal occasions.",
      descriptionAr: "جلابة رجالية جزائرية كلاسيكية من القطن الأبيض، مثالية للمناسبات الرسمية.",
      descriptionFr: "Djellaba classique algérienne pour homme en coton blanc, idéale pour les occasions formelles.",
      price: "5500",
      originalPrice: "6500",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1580657018950-c7f7d6a6d990?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1580657018950-c7f7d6a6d990?w=600&q=80"],
      categoryId: catMap["clothing"],
      inStock: true,
      stockQuantity: 50,
      rating: "4.7",
      reviewCount: 92,
      isFeatured: false,
      discount: 15,
      brand: "Tlemcen Mode",
      sku: "CLT-DJL-M-W",
      tags: ["djellaba", "traditional", "algerian", "men"],
      specifications: { "Material": "100% Cotton", "Color": "White", "Size": "S, M, L, XL, XXL" },
    },
    {
      name: "Women's Kaftan",
      nameAr: "قفطان نسائي",
      nameFr: "Kaftan Femme",
      slug: "womens-kaftan",
      description: "Elegant embroidered kaftan for special occasions and celebrations.",
      descriptionAr: "قفطان مطرز أنيق للمناسبات الخاصة والاحتفالات.",
      descriptionFr: "Kaftan brodé élégant pour occasions spéciales et célébrations.",
      price: "12000",
      originalPrice: "15000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1590735213920-68192a487bc2?w=600&q=80"],
      categoryId: catMap["clothing"],
      inStock: true,
      stockQuantity: 20,
      rating: "4.8",
      reviewCount: 67,
      isFeatured: true,
      discount: 20,
      brand: "Constantine Élégance",
      sku: "CLT-KFT-W",
      tags: ["kaftan", "traditional", "women", "elegant"],
      specifications: { "Material": "Silk-Blend", "Embroidery": "Handmade", "Size": "S, M, L, XL" },
    },
    // Home & Kitchen
    {
      name: "Traditional Tagine Pot",
      nameAr: "طاجين تقليدي",
      nameFr: "Tajine Traditionnel",
      slug: "traditional-tagine",
      description: "Authentic handcrafted clay tagine pot for traditional Algerian cuisine.",
      descriptionAr: "وعاء طاجين طيني مصنوع يدويًا للمطبخ الجزائري التقليدي.",
      descriptionFr: "Tajine en argile artisanale authentique pour la cuisine algérienne traditionnelle.",
      price: "3200",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80"],
      categoryId: catMap["home-kitchen"],
      inStock: true,
      stockQuantity: 80,
      rating: "4.9",
      reviewCount: 234,
      isFeatured: true,
      brand: "Poterie Berbère",
      sku: "HK-TGN-CL",
      tags: ["tagine", "kitchen", "traditional", "clay"],
      specifications: { "Material": "Clay", "Capacity": "3 Liters", "Size": "30 cm", "Origin": "Kabylie" },
    },
    {
      name: "Coffee Set - Moroccan Style",
      nameAr: "طقم قهوة على الطراز المغاربي",
      nameFr: "Service à Café Style Maghrébin",
      slug: "maghrebi-coffee-set",
      description: "Beautiful ornate coffee set with tray, perfect for Algerian hospitality.",
      descriptionAr: "طقم قهوة مزخرف جميل مع صينية، مثالي للضيافة الجزائرية.",
      descriptionFr: "Beau service à café orné avec plateau, parfait pour l'hospitalité algérienne.",
      price: "4500",
      originalPrice: "5500",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1525904099612-a8ca9c5c3e48?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1525904099612-a8ca9c5c3e48?w=600&q=80"],
      categoryId: catMap["home-kitchen"],
      inStock: true,
      stockQuantity: 35,
      rating: "4.6",
      reviewCount: 88,
      isFeatured: false,
      discount: 18,
      brand: "Artisan d'Alger",
      sku: "HK-CF-SET",
      tags: ["coffee", "kitchen", "set", "traditional"],
      specifications: { "Pieces": "6 cups + tray", "Material": "Ceramic & Brass", "Color": "Gold & White" },
    },
    {
      name: "Pressure Cooker 10L",
      nameAr: "قدر ضغط 10 لتر",
      nameFr: "Cocotte-Minute 10L",
      slug: "pressure-cooker-10l",
      description: "Heavy-duty stainless steel pressure cooker for large families.",
      descriptionAr: "قدر ضغط من الفولاذ المقاوم للصدأ للعائلات الكبيرة.",
      descriptionFr: "Cocotte-minute en acier inoxydable robuste pour les grandes familles.",
      price: "6800",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80"],
      categoryId: catMap["home-kitchen"],
      inStock: true,
      stockQuantity: 40,
      rating: "4.4",
      reviewCount: 112,
      isFeatured: false,
      brand: "Tefal",
      sku: "HK-PC-10L",
      tags: ["pressure cooker", "kitchen", "cooking"],
      specifications: { "Capacity": "10 Liters", "Material": "Stainless Steel", "Safety": "Multi-safety system" },
    },
    // Beauty
    {
      name: "Argan Oil Premium 100ml",
      nameAr: "زيت أرغان فاخر 100 مل",
      nameFr: "Huile d'Argan Premium 100ml",
      slug: "argan-oil-100ml",
      description: "Pure cold-pressed Algerian argan oil for hair and skin care.",
      descriptionAr: "زيت أرغان جزائري نقي مستخلص بالضغط البارد للشعر والعناية بالبشرة.",
      descriptionFr: "Huile d'argan algérienne pure pressée à froid pour les soins capillaires et cutanés.",
      price: "2800",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80"],
      categoryId: catMap["beauty"],
      inStock: true,
      stockQuantity: 100,
      rating: "4.9",
      reviewCount: 345,
      isFeatured: true,
      brand: "Naturel DZ",
      sku: "BT-ARG-100",
      tags: ["argan", "oil", "hair", "skin", "natural"],
      specifications: { "Volume": "100 ml", "Type": "Cold-pressed", "Pure": "100%", "Origin": "Algeria" },
    },
    {
      name: "Ghassoul Clay Mask",
      nameAr: "قناع الغاسول الطيني",
      nameFr: "Masque à l'Argile Ghassoul",
      slug: "ghassoul-clay-mask",
      description: "Natural Moroccan ghassoul clay mask for deep skin cleansing.",
      descriptionAr: "قناع طيني غاسول طبيعي لتنظيف البشرة العميق.",
      descriptionFr: "Masque à l'argile ghassoul naturel pour un nettoyage en profondeur de la peau.",
      price: "1500",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80"],
      categoryId: catMap["beauty"],
      inStock: true,
      stockQuantity: 200,
      rating: "4.7",
      reviewCount: 189,
      isFeatured: false,
      brand: "Naturel DZ",
      sku: "BT-GHL-200",
      tags: ["ghassoul", "mask", "clay", "natural"],
      specifications: { "Weight": "200 g", "Skin Type": "All types", "Usage": "Weekly" },
    },
    // Sports
    {
      name: "Football (Soccer Ball) Adidas",
      nameAr: "كرة القدم أديداس",
      nameFr: "Ballon de Football Adidas",
      slug: "adidas-football",
      description: "Professional grade football for training and matches.",
      descriptionAr: "كرة قدم بدرجة احترافية للتدريب والمباريات.",
      descriptionFr: "Ballon de football de qualité professionnelle pour l'entraînement et les matchs.",
      price: "3500",
      originalPrice: "4200",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1614632537239-e2258ccae47e?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1614632537239-e2258ccae47e?w=600&q=80"],
      categoryId: catMap["sports"],
      inStock: true,
      stockQuantity: 60,
      rating: "4.6",
      reviewCount: 143,
      isFeatured: true,
      discount: 17,
      brand: "Adidas",
      sku: "SP-FB-ADI",
      tags: ["football", "adidas", "sports", "outdoor"],
      specifications: { "Size": "5", "Material": "Synthetic Leather", "Weight": "410-450 g" },
    },
    {
      name: "Running Shoes Nike Air Max",
      nameAr: "حذاء الجري نايك إير ماكس",
      nameFr: "Chaussures de Course Nike Air Max",
      slug: "nike-air-max-running",
      description: "Comfortable running shoes with Air Max cushioning technology.",
      descriptionAr: "أحذية جري مريحة بتقنية وسادة Air Max.",
      descriptionFr: "Chaussures de course confortables avec technologie de coussin Air Max.",
      price: "18000",
      originalPrice: "22000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80"],
      categoryId: catMap["sports"],
      inStock: true,
      stockQuantity: 35,
      rating: "4.7",
      reviewCount: 98,
      isFeatured: true,
      discount: 18,
      brand: "Nike",
      sku: "SP-NK-AM",
      tags: ["running", "nike", "shoes", "sports"],
      specifications: { "Material": "Mesh & Synthetic", "Sole": "Air Max", "Size": "40-46", "Gender": "Unisex" },
    },
    // Food
    {
      name: "Deglet Nour Dates 1kg",
      nameAr: "تمور دقلة النور 1 كغ",
      nameFr: "Dattes Deglet Nour 1kg",
      slug: "deglet-nour-dates-1kg",
      description: "Premium Deglet Nour dates from Biskra, Algeria. Sweet and naturally soft.",
      descriptionAr: "تمور دقلة النور الفاخرة من بسكرة، الجزائر. حلوة وطرية طبيعيًا.",
      descriptionFr: "Dattes Deglet Nour premium de Biskra, Algérie. Douces et naturellement moelleuses.",
      price: "1800",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1594671517673-1e4b5a0c76be?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1594671517673-1e4b5a0c76be?w=600&q=80"],
      categoryId: catMap["food"],
      inStock: true,
      stockQuantity: 500,
      rating: "4.9",
      reviewCount: 567,
      isFeatured: true,
      brand: "Sahara Gold",
      sku: "FD-DGN-1K",
      tags: ["dates", "deglet nour", "biskra", "algerian"],
      specifications: { "Weight": "1 kg", "Origin": "Biskra, Algeria", "Type": "Deglet Nour", "Storage": "Cool & dry" },
    },
    {
      name: "Couscous Extra Fine 2kg",
      nameAr: "كسكس ناعم جدا 2 كغ",
      nameFr: "Couscous Extra Fin 2kg",
      slug: "couscous-extra-fine-2kg",
      description: "Traditional Algerian extra fine couscous, perfect for all couscous dishes.",
      descriptionAr: "كسكس جزائري تقليدي ناعم جدًا، مثالي لجميع أطباق الكسكس.",
      descriptionFr: "Couscous algérien extra fin traditionnel, parfait pour tous les plats de couscous.",
      price: "450",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80"],
      categoryId: catMap["food"],
      inStock: true,
      stockQuantity: 1000,
      rating: "4.8",
      reviewCount: 423,
      isFeatured: false,
      brand: "Bimo",
      sku: "FD-CSC-2K",
      tags: ["couscous", "algerian", "food", "traditional"],
      specifications: { "Weight": "2 kg", "Type": "Extra Fine", "Origin": "Algeria" },
    },
    {
      name: "Olive Oil Extra Virgin 1L",
      nameAr: "زيت زيتون بكر ممتاز 1 لتر",
      nameFr: "Huile d'Olive Extra Vierge 1L",
      slug: "olive-oil-extra-virgin-1l",
      description: "Premium extra virgin olive oil from Algerian olive groves.",
      descriptionAr: "زيت زيتون بكر ممتاز فاخر من بساتين الزيتون الجزائرية.",
      descriptionFr: "Huile d'olive extra vierge premium des oliveraies algériennes.",
      price: "1200",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80"],
      categoryId: catMap["food"],
      inStock: true,
      stockQuantity: 300,
      rating: "4.8",
      reviewCount: 312,
      isFeatured: true,
      brand: "Ifri",
      sku: "FD-OLV-1L",
      tags: ["olive oil", "algerian", "food", "healthy"],
      specifications: { "Volume": "1 L", "Type": "Extra Virgin", "Origin": "Kabylie, Algeria", "Acidity": "< 0.5%" },
    },
    // Books
    {
      name: "Arabic Dictionary - Larousse",
      nameAr: "قاموس عربي - لاروس",
      nameFr: "Dictionnaire Arabe - Larousse",
      slug: "arabic-dictionary-larousse",
      description: "Comprehensive Arabic dictionary with translations and grammar rules.",
      descriptionAr: "قاموس عربي شامل مع الترجمات وقواعد النحو.",
      descriptionFr: "Dictionnaire arabe complet avec traductions et règles grammaticales.",
      price: "2500",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80"],
      categoryId: catMap["books"],
      inStock: true,
      stockQuantity: 150,
      rating: "4.7",
      reviewCount: 67,
      isFeatured: false,
      brand: "Larousse",
      sku: "BK-ARB-LAR",
      tags: ["dictionary", "arabic", "education"],
      specifications: { "Language": "Arabic-French", "Pages": "1200", "Publisher": "Larousse", "Edition": "2022" },
    },
    // Toys
    {
      name: "LEGO City Police Station",
      nameAr: "ليغو سيتي مركز الشرطة",
      nameFr: "LEGO City Poste de Police",
      slug: "lego-city-police-station",
      description: "Fun and educational LEGO City Police Station building set for kids.",
      descriptionAr: "مجموعة بناء مركز الشرطة التعليمية والممتعة من ليغو سيتي للأطفال.",
      descriptionFr: "Jeu de construction LEGO City Poste de Police amusant et éducatif pour les enfants.",
      price: "7500",
      originalPrice: "9000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&q=80"],
      categoryId: catMap["toys"],
      inStock: true,
      stockQuantity: 25,
      rating: "4.8",
      reviewCount: 134,
      isFeatured: true,
      discount: 17,
      brand: "LEGO",
      sku: "TY-LGO-PLC",
      tags: ["lego", "toys", "kids", "building"],
      specifications: { "Pieces": "668", "Age": "6+", "Theme": "City" },
    },
    // Automotive
    {
      name: "Car Dash Camera Full HD",
      nameAr: "كاميرا لوحة تحكم السيارة Full HD",
      nameFr: "Caméra de Tableau de Bord Full HD",
      slug: "car-dash-camera-full-hd",
      description: "Full HD 1080p dash camera with night vision and loop recording.",
      descriptionAr: "كاميرا لوحة تحكم بدقة Full HD 1080p مع رؤية ليلية وتسجيل دوار.",
      descriptionFr: "Caméra de tableau de bord Full HD 1080p avec vision nocturne et enregistrement en boucle.",
      price: "5500",
      originalPrice: "7000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
      categoryId: catMap["automotive"],
      inStock: true,
      stockQuantity: 55,
      rating: "4.4",
      reviewCount: 98,
      isFeatured: false,
      discount: 21,
      brand: "AutoCam",
      sku: "AUT-DCM-FHD",
      tags: ["dash cam", "car", "camera", "safety"],
      specifications: { "Resolution": "1080p Full HD", "Night Vision": "Yes", "Memory": "Up to 128 GB SD", "Angle": "170°" },
    },
    // Handicrafts
    {
      name: "Berber Carpet - Traditional Pattern",
      nameAr: "زربية بربرية - نمط تقليدي",
      nameFr: "Tapis Berbère - Motif Traditionnel",
      slug: "berber-carpet-traditional",
      description: "Hand-woven Berber carpet with authentic geometric patterns from Kabylie.",
      descriptionAr: "زربية بربرية منسوجة يدويًا بأنماط هندسية أصيلة من القبائل.",
      descriptionFr: "Tapis berbère tissé à la main avec des motifs géométriques authentiques de Kabylie.",
      price: "15000",
      currency: "DZD",
      image: "https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=600&q=80",
      images: ["https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=600&q=80"],
      categoryId: catMap["handicrafts"],
      inStock: true,
      stockQuantity: 15,
      rating: "4.9",
      reviewCount: 78,
      isFeatured: true,
      brand: "Tisseuses de Kabylie",
      sku: "HC-BRB-CPT",
      tags: ["berber", "carpet", "traditional", "algerian", "handmade"],
      specifications: { "Size": "150x200 cm", "Material": "Wool", "Origin": "Kabylie, Algeria", "Pattern": "Traditional Geometric" },
    },
  ];

  const existingProducts = seedMode === "bootstrap" ? await db.select().from(productsTable) : [];
  const existingProductSlugs = new Set(existingProducts.map((product) => product.slug));
  const missingProducts = productSeeds.filter((product) => !existingProductSlugs.has(product.slug));

  if (missingProducts.length > 0) {
    await db.insert(productsTable).values(missingProducts);
  }

  const products = await db.select().from(productsTable);
  if (seedMode === "reset") {
    console.log(`Inserted ${products.length} products`);
  } else if (missingProducts.length > 0) {
    console.log(`Inserted ${missingProducts.length} missing products`);
  } else {
    console.log(`Skipped products; ${products.length} already present`);
  }

  // Wilayas (all 48 main wilayas of Algeria)
  const wilayaSeeds: InsertWilaya[] = [
    { code: "01", name: "Adrar", nameAr: "أدرار", nameFr: "Adrar" },
    { code: "02", name: "Chlef", nameAr: "الشلف", nameFr: "Chlef" },
    { code: "03", name: "Laghouat", nameAr: "الأغواط", nameFr: "Laghouat" },
    { code: "04", name: "Oum El Bouaghi", nameAr: "أم البواقي", nameFr: "Oum El Bouaghi" },
    { code: "05", name: "Batna", nameAr: "باتنة", nameFr: "Batna" },
    { code: "06", name: "Béjaïa", nameAr: "بجاية", nameFr: "Béjaïa" },
    { code: "07", name: "Biskra", nameAr: "بسكرة", nameFr: "Biskra" },
    { code: "08", name: "Béchar", nameAr: "بشار", nameFr: "Béchar" },
    { code: "09", name: "Blida", nameAr: "البليدة", nameFr: "Blida" },
    { code: "10", name: "Bouira", nameAr: "البويرة", nameFr: "Bouira" },
    { code: "11", name: "Tamanrasset", nameAr: "تمنراست", nameFr: "Tamanrasset" },
    { code: "12", name: "Tébessa", nameAr: "تبسة", nameFr: "Tébessa" },
    { code: "13", name: "Tlemcen", nameAr: "تلمسان", nameFr: "Tlemcen" },
    { code: "14", name: "Tiaret", nameAr: "تيارت", nameFr: "Tiaret" },
    { code: "15", name: "Tizi Ouzou", nameAr: "تيزي وزو", nameFr: "Tizi Ouzou" },
    { code: "16", name: "Algiers", nameAr: "الجزائر", nameFr: "Alger" },
    { code: "17", name: "Djelfa", nameAr: "الجلفة", nameFr: "Djelfa" },
    { code: "18", name: "Jijel", nameAr: "جيجل", nameFr: "Jijel" },
    { code: "19", name: "Sétif", nameAr: "سطيف", nameFr: "Sétif" },
    { code: "20", name: "Saïda", nameAr: "سعيدة", nameFr: "Saïda" },
    { code: "21", name: "Skikda", nameAr: "سكيكدة", nameFr: "Skikda" },
    { code: "22", name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", nameFr: "Sidi Bel Abbès" },
    { code: "23", name: "Annaba", nameAr: "عنابة", nameFr: "Annaba" },
    { code: "24", name: "Guelma", nameAr: "قالمة", nameFr: "Guelma" },
    { code: "25", name: "Constantine", nameAr: "قسنطينة", nameFr: "Constantine" },
    { code: "26", name: "Médéa", nameAr: "المدية", nameFr: "Médéa" },
    { code: "27", name: "Mostaganem", nameAr: "مستغانم", nameFr: "Mostaganem" },
    { code: "28", name: "M'Sila", nameAr: "المسيلة", nameFr: "M'Sila" },
    { code: "29", name: "Mascara", nameAr: "معسكر", nameFr: "Mascara" },
    { code: "30", name: "Ouargla", nameAr: "ورقلة", nameFr: "Ouargla" },
    { code: "31", name: "Oran", nameAr: "وهران", nameFr: "Oran" },
    { code: "32", name: "El Bayadh", nameAr: "البيض", nameFr: "El Bayadh" },
    { code: "33", name: "Illizi", nameAr: "إليزي", nameFr: "Illizi" },
    { code: "34", name: "Bordj Bou Arréridj", nameAr: "برج بوعريريج", nameFr: "Bordj Bou Arréridj" },
    { code: "35", name: "Boumerdès", nameAr: "بومرداس", nameFr: "Boumerdès" },
    { code: "36", name: "El Tarf", nameAr: "الطارف", nameFr: "El Tarf" },
    { code: "37", name: "Tindouf", nameAr: "تندوف", nameFr: "Tindouf" },
    { code: "38", name: "Tissemsilt", nameAr: "تيسمسيلت", nameFr: "Tissemsilt" },
    { code: "39", name: "El Oued", nameAr: "الوادي", nameFr: "El Oued" },
    { code: "40", name: "Khenchela", nameAr: "خنشلة", nameFr: "Khenchela" },
    { code: "41", name: "Souk Ahras", nameAr: "سوق أهراس", nameFr: "Souk Ahras" },
    { code: "42", name: "Tipaza", nameAr: "تيبازة", nameFr: "Tipaza" },
    { code: "43", name: "Mila", nameAr: "ميلة", nameFr: "Mila" },
    { code: "44", name: "Aïn Defla", nameAr: "عين الدفلى", nameFr: "Aïn Defla" },
    { code: "45", name: "Naâma", nameAr: "النعامة", nameFr: "Naâma" },
    { code: "46", name: "Aïn Témouchent", nameAr: "عين تموشنت", nameFr: "Aïn Témouchent" },
    { code: "47", name: "Ghardaïa", nameAr: "غرداية", nameFr: "Ghardaïa" },
    { code: "48", name: "Relizane", nameAr: "غليزان", nameFr: "Relizane" },
    { code: "49", name: "Timimoun", nameAr: "تيميمون", nameFr: "Timimoun" },
    { code: "50", name: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار", nameFr: "Bordj Badji Mokhtar" },
    { code: "51", name: "Ouled Djellal", nameAr: "أولاد جلال", nameFr: "Ouled Djellal" },
    { code: "52", name: "Béni Abbès", nameAr: "بني عباس", nameFr: "Béni Abbès" },
    { code: "53", name: "In Salah", nameAr: "عين صالح", nameFr: "In Salah" },
    { code: "54", name: "In Guezzam", nameAr: "عين قزام", nameFr: "In Guezzam" },
    { code: "55", name: "Touggourt", nameAr: "تقرت", nameFr: "Touggourt" },
    { code: "56", name: "Djanet", nameAr: "جانت", nameFr: "Djanet" },
    { code: "57", name: "El M'Ghair", nameAr: "المغير", nameFr: "El M'Ghair" },
    { code: "58", name: "El Meniaa", nameAr: "المنيعة", nameFr: "El Meniaa" },
  ];

  const existingWilayas = seedMode === "bootstrap" ? await db.select().from(wilayasTable) : [];
  const existingWilayaCodes = new Set(existingWilayas.map((wilaya) => wilaya.code));
  const missingWilayas = wilayaSeeds.filter((wilaya) => !existingWilayaCodes.has(wilaya.code));

  if (missingWilayas.length > 0) {
    await db.insert(wilayasTable).values(missingWilayas);
  }

  const wilayas = await db.select().from(wilayasTable);
  if (seedMode === "reset") {
    console.log(`Inserted ${wilayas.length} wilayas`);
  } else if (missingWilayas.length > 0) {
    console.log(`Inserted ${missingWilayas.length} missing wilayas`);
  } else {
    console.log(`Skipped wilayas; ${wilayas.length} already present`);
  }

  // Cities for major wilayas
  const citySeeds: InsertCity[] = [
    // Algiers (16)
    { name: "Algiers Center", nameAr: "وسط الجزائر", nameFr: "Alger Centre", wilayaCode: "16" },
    { name: "Bab El Oued", nameAr: "باب الواد", nameFr: "Bab El Oued", wilayaCode: "16" },
    { name: "El Harrach", nameAr: "الحراش", nameFr: "El Harrach", wilayaCode: "16" },
    { name: "Kouba", nameAr: "القبة", nameFr: "Kouba", wilayaCode: "16" },
    { name: "Hussein Dey", nameAr: "حسين داي", nameFr: "Hussein Dey", wilayaCode: "16" },
    { name: "Bir Mourad Raïs", nameAr: "بئر مراد رايس", nameFr: "Bir Mourad Raïs", wilayaCode: "16" },
    { name: "Birkhadem", nameAr: "بئر خادم", nameFr: "Birkhadem", wilayaCode: "16" },
    { name: "Dar El Beïda", nameAr: "الدار البيضاء", nameFr: "Dar El Beïda", wilayaCode: "16" },
    { name: "Rouiba", nameAr: "رويبة", nameFr: "Rouiba", wilayaCode: "16" },
    // Oran (31)
    { name: "Oran", nameAr: "وهران", nameFr: "Oran", wilayaCode: "31" },
    { name: "Es Sénia", nameAr: "السانية", nameFr: "Es Sénia", wilayaCode: "31" },
    { name: "Bir El Djir", nameAr: "بئر الجير", nameFr: "Bir El Djir", wilayaCode: "31" },
    { name: "Hassi Bounif", nameAr: "حاسي بونيف", nameFr: "Hassi Bounif", wilayaCode: "31" },
    // Constantine (25)
    { name: "Constantine", nameAr: "قسنطينة", nameFr: "Constantine", wilayaCode: "25" },
    { name: "El Khroub", nameAr: "الخروب", nameFr: "El Khroub", wilayaCode: "25" },
    { name: "Hamma Bouziane", nameAr: "حامة بوزيان", nameFr: "Hamma Bouziane", wilayaCode: "25" },
    // Annaba (23)
    { name: "Annaba", nameAr: "عنابة", nameFr: "Annaba", wilayaCode: "23" },
    { name: "El Bouni", nameAr: "البوني", nameFr: "El Bouni", wilayaCode: "23" },
    { name: "El Hadjar", nameAr: "الحجار", nameFr: "El Hadjar", wilayaCode: "23" },
    // Sétif (19)
    { name: "Sétif", nameAr: "سطيف", nameFr: "Sétif", wilayaCode: "19" },
    { name: "El Eulma", nameAr: "العلمة", nameFr: "El Eulma", wilayaCode: "19" },
    { name: "Aïn Arnat", nameAr: "عين أرنات", nameFr: "Aïn Arnat", wilayaCode: "19" },
    // Batna (05)
    { name: "Batna", nameAr: "باتنة", nameFr: "Batna", wilayaCode: "05" },
    { name: "Barika", nameAr: "بريكة", nameFr: "Barika", wilayaCode: "05" },
    // Blida (09)
    { name: "Blida", nameAr: "البليدة", nameFr: "Blida", wilayaCode: "09" },
    { name: "Boufarik", nameAr: "بوفاريك", nameFr: "Boufarik", wilayaCode: "09" },
    { name: "Larbaa", nameAr: "لاربعاء", nameFr: "Larbaa", wilayaCode: "09" },
    // Tizi Ouzou (15)
    { name: "Tizi Ouzou", nameAr: "تيزي وزو", nameFr: "Tizi Ouzou", wilayaCode: "15" },
    { name: "Azazga", nameAr: "عزازقة", nameFr: "Azazga", wilayaCode: "15" },
    { name: "Draa El Mizan", nameAr: "ذراع الميزان", nameFr: "Draa El Mizan", wilayaCode: "15" },
    // Béjaïa (06)
    { name: "Béjaïa", nameAr: "بجاية", nameFr: "Béjaïa", wilayaCode: "06" },
    { name: "Akbou", nameAr: "أقبو", nameFr: "Akbou", wilayaCode: "06" },
    // Tlemcen (13)
    { name: "Tlemcen", nameAr: "تلمسان", nameFr: "Tlemcen", wilayaCode: "13" },
    { name: "Maghnia", nameAr: "مغنية", nameFr: "Maghnia", wilayaCode: "13" },
    // Biskra (07)
    { name: "Biskra", nameAr: "بسكرة", nameFr: "Biskra", wilayaCode: "07" },
    { name: "Tolga", nameAr: "طولقة", nameFr: "Tolga", wilayaCode: "07" },
    // Ouargla (30)
    { name: "Ouargla", nameAr: "ورقلة", nameFr: "Ouargla", wilayaCode: "30" },
    { name: "Hassi Messaoud", nameAr: "حاسي مسعود", nameFr: "Hassi Messaoud", wilayaCode: "30" },
    // Boumerdès (35)
    { name: "Boumerdès", nameAr: "بومرداس", nameFr: "Boumerdès", wilayaCode: "35" },
    { name: "Bordj Ménaïel", nameAr: "برج منايل", nameFr: "Bordj Ménaïel", wilayaCode: "35" },
    // Others - one city each for remaining wilayas
    { name: "Adrar", nameAr: "أدرار", nameFr: "Adrar", wilayaCode: "01" },
    { name: "Chlef", nameAr: "الشلف", nameFr: "Chlef", wilayaCode: "02" },
    { name: "Laghouat", nameAr: "الأغواط", nameFr: "Laghouat", wilayaCode: "03" },
    { name: "Oum El Bouaghi", nameAr: "أم البواقي", nameFr: "Oum El Bouaghi", wilayaCode: "04" },
    { name: "Béchar", nameAr: "بشار", nameFr: "Béchar", wilayaCode: "08" },
    { name: "Bouira", nameAr: "البويرة", nameFr: "Bouira", wilayaCode: "10" },
    { name: "Tamanrasset", nameAr: "تمنراست", nameFr: "Tamanrasset", wilayaCode: "11" },
    { name: "Tébessa", nameAr: "تبسة", nameFr: "Tébessa", wilayaCode: "12" },
    { name: "Tiaret", nameAr: "تيارت", nameFr: "Tiaret", wilayaCode: "14" },
    { name: "Djelfa", nameAr: "الجلفة", nameFr: "Djelfa", wilayaCode: "17" },
    { name: "Jijel", nameAr: "جيجل", nameFr: "Jijel", wilayaCode: "18" },
    { name: "Saïda", nameAr: "سعيدة", nameFr: "Saïda", wilayaCode: "20" },
    { name: "Skikda", nameAr: "سكيكدة", nameFr: "Skikda", wilayaCode: "21" },
    { name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", nameFr: "Sidi Bel Abbès", wilayaCode: "22" },
    { name: "Guelma", nameAr: "قالمة", nameFr: "Guelma", wilayaCode: "24" },
    { name: "Médéa", nameAr: "المدية", nameFr: "Médéa", wilayaCode: "26" },
    { name: "Mostaganem", nameAr: "مستغانم", nameFr: "Mostaganem", wilayaCode: "27" },
    { name: "M'Sila", nameAr: "المسيلة", nameFr: "M'Sila", wilayaCode: "28" },
    { name: "Mascara", nameAr: "معسكر", nameFr: "Mascara", wilayaCode: "29" },
    { name: "El Bayadh", nameAr: "البيض", nameFr: "El Bayadh", wilayaCode: "32" },
    { name: "Illizi", nameAr: "إليزي", nameFr: "Illizi", wilayaCode: "33" },
    { name: "Bordj Bou Arréridj", nameAr: "برج بوعريريج", nameFr: "Bordj Bou Arréridj", wilayaCode: "34" },
    { name: "El Tarf", nameAr: "الطارف", nameFr: "El Tarf", wilayaCode: "36" },
    { name: "Tindouf", nameAr: "تندوف", nameFr: "Tindouf", wilayaCode: "37" },
    { name: "Tissemsilt", nameAr: "تيسمسيلت", nameFr: "Tissemsilt", wilayaCode: "38" },
    { name: "El Oued", nameAr: "الوادي", nameFr: "El Oued", wilayaCode: "39" },
    { name: "Khenchela", nameAr: "خنشلة", nameFr: "Khenchela", wilayaCode: "40" },
    { name: "Souk Ahras", nameAr: "سوق أهراس", nameFr: "Souk Ahras", wilayaCode: "41" },
    { name: "Tipaza", nameAr: "تيبازة", nameFr: "Tipaza", wilayaCode: "42" },
    { name: "Mila", nameAr: "ميلة", nameFr: "Mila", wilayaCode: "43" },
    { name: "Aïn Defla", nameAr: "عين الدفلى", nameFr: "Aïn Defla", wilayaCode: "44" },
    { name: "Naâma", nameAr: "النعامة", nameFr: "Naâma", wilayaCode: "45" },
    { name: "Aïn Témouchent", nameAr: "عين تموشنت", nameFr: "Aïn Témouchent", wilayaCode: "46" },
    { name: "Ghardaïa", nameAr: "غرداية", nameFr: "Ghardaïa", wilayaCode: "47" },
    { name: "Relizane", nameAr: "غليزان", nameFr: "Relizane", wilayaCode: "48" },
    { name: "Timimoun", nameAr: "تيميمون", nameFr: "Timimoun", wilayaCode: "49" },
    { name: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار", nameFr: "Bordj Badji Mokhtar", wilayaCode: "50" },
    { name: "Ouled Djellal", nameAr: "أولاد جلال", nameFr: "Ouled Djellal", wilayaCode: "51" },
    { name: "Béni Abbès", nameAr: "بني عباس", nameFr: "Béni Abbès", wilayaCode: "52" },
    { name: "In Salah", nameAr: "عين صالح", nameFr: "In Salah", wilayaCode: "53" },
    { name: "In Guezzam", nameAr: "عين قزام", nameFr: "In Guezzam", wilayaCode: "54" },
    { name: "Touggourt", nameAr: "تقرت", nameFr: "Touggourt", wilayaCode: "55" },
    { name: "Djanet", nameAr: "جانت", nameFr: "Djanet", wilayaCode: "56" },
    { name: "El M'Ghair", nameAr: "المغير", nameFr: "El M'Ghair", wilayaCode: "57" },
    { name: "El Meniaa", nameAr: "المنيعة", nameFr: "El Meniaa", wilayaCode: "58" },
  ];

  const existingCities = seedMode === "bootstrap" ? await db.select().from(citiesTable) : [];
  const existingCityKeys = new Set(existingCities.map((city) => `${city.wilayaCode}:${city.name}`));
  const missingCities = citySeeds.filter((city) => !existingCityKeys.has(`${city.wilayaCode}:${city.name}`));

  if (missingCities.length > 0) {
    await db.insert(citiesTable).values(missingCities);
  }

  const cities = await db.select().from(citiesTable);
  if (seedMode === "reset") {
    console.log(`Inserted ${cities.length} cities`);
  } else if (missingCities.length > 0) {
    console.log(`Inserted ${missingCities.length} missing cities`);
  } else {
    console.log(`Skipped cities; ${cities.length} already present`);
  }
  console.log("✅ Seed complete!");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
